<?php

namespace Site\BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	  public function findByNews()
  {
     $qb = $this->createQueryBuilder('a');

  $qb
    ->where( 'a.published = 1')
    ->orderBy('a.date', 'DESC')
    ->setMaxResults(2)
    ;

     return $qb
    ->getQuery()
    ->getResult()
    ;
  }
}
