<?php

namespace Site\BlogBundle\Repository;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{

	public function getByProduct($productId)
  {
    $qb = $this->createQueryBuilder('c')
               ->select('COUNT(c)')
               ->where('c.product = :id')
               ->setParameter('id', $productId);
    return $qb->getQuery()
              ->getSingleScalarResult();
  }


  public function getByService()
  {
    
  }


  public function findByGetPublished()
  {
     $qb = $this->createQueryBuilder('a');

 	$qb
    ->where( 'a.published = 1')
    ->orderBy('a.date', 'DESC')
  	;

  	 return $qb
    ->getQuery()
    ->getResult()
    ;
  }


}
