admin_blog_view:
    path:     /{slug}
    defaults:
        _controller: SiteBlogBundle:BlogAdmin:view 

admin_blog_add:
    path:    /add/article
    defaults: 
        _controller: SiteBlogBundle:BlogAdmin:add 

admin_blog_list:
    path:    /list/article
    defaults: 
        _controller: SiteBlogBundle:BlogAdmin:listArticle

admin_blog_edit:
    path:    /edit/{slug}
    defaults: 
        _controller: SiteBlogBundle:BlogAdmin:edit 
    requirements:
        id: \d+

admin_blog_delete:
    path:   /delete/{slug}
    defaults: 
        _controller: SiteBlogBundle:BlogAdmin:delete 
    requirements:
        id: \d+

